// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProgiAPI.DbModels;

public partial class BuyerSellerFees
{
    public int Id { get; set; }

    public int? CarTypeId { get; set; }
    public string FeeType { get; set; }

    public int? percentage { get; set; }

    public int? min_value { get; set; }

    public int? max_value { get; set; }

    //public virtual CarTypes CarType { get; set; }
}