// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProgiAPI.DbModels;

public partial class StorageFee
{
    public int Id { get; set; }
    
    public int fee_amount { get; set; }
}